[workspace]
members = [
    "crates/types",
    "crates/types-main",
    "crates/records",
    "crates/records-main",
    "crates/flags",
    "crates/flags-main",
    "crates/lists",
    "crates/lists-main",
    "crates/variants",
    "crates/variants-main",
]
