[package]
name = "markdown"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = "0.8.0"
witx-bindgen-rust = { git = "https://github.com/bytecodealliance/witx-bindgen", branch = "main" }

[workspace]
