[package]
name = "variants"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
witx-bindgen-rust = { path = "../../../../rust-wasm" }
