[package]
name = "witx-bindgen-wasmtime"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
witx-bindgen-wasmtime-impl = { path = "../wasmtime-impl", version = "0.1" }
wasmtime = "0.23"
anyhow = "1.0"
