[package]
name = "resources"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
witx-bindgen-rust = { path = "../../../../rust-wasm" }
